### ISSUE TITLE
Annotation EnableDiscoveryClient is absent?

### ISSUE THREAD

**Issue by KolyaMetallist** [aabarmin/epam-microservices-training-2021#25]
https://github.com/aabarmin/epam-microservices-training-2021/blob/3207405d7b7c4c663868ff59863f924b8355f425/microservices/microservice-recipies/src/main/java/com/epam/training/microservice/service/recipes/RecipesServiceApplication.java#L15

This SpringBoot app has no `@EnableDiscoveryClient` in contrast to other Microservice apps in the same project. Nevertheless it connects to Eureka Server successfully. Is that expected?

**Comment by aabarmin** [comment]
Well, there is a Eureka dependency, so, it works even without the annotation but nevertheless, I'll add it. 
Good catch, thank you.

**Comment by aabarmin** [comment]
Fixed in #26
